# Generated by Django 4.0.5 on 2022-06-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_warehouseimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Название компании')),
                ('key_word', models.CharField(max_length=256, verbose_name='Ключевое слово')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('clicks', models.IntegerField(default=0, verbose_name='Число кликов')),
            ],
            options={
                'verbose_name': 'Рекламная компания',
                'verbose_name_plural': 'Рекламные компании',
                'ordering': ('title',),
            },
        ),
    ]
