# Generated by Django 4.0.5 on 2022-06-17 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0012_alter_lease_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='leaves/', verbose_name='QR code'),
        ),
    ]
