version: '3.8'

services:
  django:
    container_name: storage-django
    build: ./src
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./src:/home/storage/web
    env_file:
      - ./src/selfstorage/.env
    depends_on:
      - db
      - redis

  db:
    container_name: storage-postgres
    image: postgres:14.0-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./src/selfstorage/.env

  redis:
    container_name: storage-redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - 6379:6379

  celery-worker:
    container_name: storage-celery-worker
    build: ./src
    restart: unless-stopped
    command: celery -A selfstorage worker -l info
    volumes:
      - ./src:/home/storage/web
    env_file:
      - ./src/selfstorage/.env
    depends_on:
      - redis

  celery-beat:
    container_name: storage-celery-beat
    build: ./src
    restart: unless-stopped
    command: celery -A selfstorage beat -l info
    volumes:
      - ./src:/home/storage/web
    env_file:
      - ./src/selfstorage/.env
    depends_on:
      - redis

volumes:
  postgres_volume:
