# Generated by Django 4.0.5 on 2022-06-18 08:58

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("storage", "0016_lease_payment_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID оплаты от Юкассы",
                    ),
                ),
                (
                    "idempotence_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="Ключ идемпотентности",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание платежа")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма платежа"
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "completed_on",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Дата завершения",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Новый"), (1, "Успешный"), (2, "Отклоненный")],
                        db_index=True,
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="storage.lease",
                        verbose_name="Элемент аренды",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
    ]
