# Generated by Django 4.0.5 on 2022-06-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
