# Generated by Django 4.0.5 on 2022-06-15 12:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("storage", "0002_warehouseimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="box",
            options={"verbose_name": "бокс", "verbose_name_plural": "боксы"},
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={"verbose_name": "склад", "verbose_name_plural": "склады"},
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Не оплачено"),
                            (1, "Оплачено"),
                            (2, "Просрочено"),
                            (3, "Завершено"),
                            (4, "Отменено"),
                        ],
                        db_index=True,
                        default=0,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата создания"
                    ),
                ),
                (
                    "paid_on",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="Дата оплаты"
                    ),
                ),
                (
                    "expires_on",
                    models.DateTimeField(verbose_name="Дата окончания аренды"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Стоимость аренды"
                    ),
                ),
                (
                    "box",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lease",
                        to="storage.box",
                        verbose_name="Бокс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Арендатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "бокс",
                "verbose_name_plural": "боксы",
            },
        ),
    ]
