# Generated by Django 4.0.5 on 2022-06-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0003_alter_box_options_alter_warehouse_options_lease"),
        ("storage", "0004_link"),
    ]

    operations = []
