# Generated by Django 4.0.5 on 2022-06-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0010_delivery_pickup_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="lease",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="QR code"
            ),
        ),
    ]
