# Generated by Django 4.0.5 on 2022-06-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0011_lease_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lease",
            name="qr_code",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="QR code"
            ),
        ),
    ]
