# Generated by Django 4.0.5 on 2022-06-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_alter_lease_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='payment_id',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='ID оплаты от Юкассы'),
        ),
    ]
