# Generated by Django 4.0.5 on 2022-06-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0016_lease_payment_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lease",
            name="paid_on",
        ),
        migrations.RemoveField(
            model_name="lease",
            name="payment_id",
        ),
    ]
