# Generated by Django 4.0.5 on 2022-06-20 10:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("storage", "0017_remove_lease_paid_on_remove_lease_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="processed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Время назначения курьера",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courier",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Курьер",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="pickup_address",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Адрес забора груза"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="registered_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Время регистрации заказа",
            ),
        ),
    ]
